name: continuous integration Action
on:
  push:
    branches: [ "develop"]
  pull_request:
    branches: [ "develop", "releases/**", "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: make application.properties
      run: |
        mkdir ./adapter-persistence/src/main/resources
        cd ./adapter-persistence/src/main/resources
        touch ./application.yaml
        echo "${{ secrets.QDANG_PROD_APPLICATION }}" >> ./application.yaml
      shell: bash
      
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: |
        ./gradlew build
