name: CI with Gradle

on:
  push:
    branches: [ "develop", "releases/**", "master" ]
  pull_request:
    branches: [ "develop", "releases/**", "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: make application.yaml
      run: |
        cd ./was/src/main/resources
        touch ./application.yaml
        echo "${{ secrets.QDANG_CI_YAML }}" > ./application.yaml
      shell: bash
      
      ## 2) 스프링 프로젝트 jar 파일 빌드
    - name: Grant execute permission for gradlew
      run: chmod +x ./was/gradlew
      
    - name: Build with Gradle
      run: ./was/gradlew build

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
#         build-root-directory: ./notification
        build-root-directory: ./was
